name: Check and Update IPs

on:
  schedule:
    - cron: '0 */10 * * *'  # 每10小时执行一次
  workflow_dispatch:

jobs:
  update-ips:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval=5s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
